TARGET_KEYWORDS = {
    't17': [
        ('bpoil',0),
        ('egypt',1),
        ('finan',2),
        ('h1n1',3),
        ('haiti',4),
        ('iraq',5),
        ('libya',6),
        ('mj',7),
        ('syria',8),
    ],
    'crisis': [
        ('libya', 1),
        ('egypt', 0),
        ('syria', 2),
        ('yemen', 3),
    ],
    'entities': [
        ('Al Gore', 0),
        ('Angela Merkel', 1),
        ('Ariel Sharon', 2),
        ('Arnold Schwarzenegger', 3),
        ('Bashar al-Assad', 4),
        ('Bill Clinton', 5),
        ('Charles Taylor', 6),
        ('Chris Brown', 7),
        ('David Beckham', 8),
        ('David Bowie', 9),
        ('Dilma Rousseff', 10),
        ('Dmitry Medvedev', 11),
        ('Dominique Strauss-Kahn', 12),
        ('Edward Snowden', 13),
        ('Ehud Olmert', 14),
        ('Enron', 15),
        ('Hamid Karzai', 16),
        ('Hassan Rouhani', 17),
        ('Hu Jintao', 18),
        ('Jacob Zuma', 19),
        ('John Boehner', 20),
        ('John Kerry', 21),
        ('Julian Assange', 22),
        ('Lance Armstrong', 23),
        ('Mahmoud Ahmadinejad', 24),
        ('Marco Rubio', 25),
        ('Margaret Thatcher', 26),
        ('Michael Jackson', 27),
        ('Michelle Obama', 28),
        ('Mitt Romney', 29),
        ('Morgan Tsvangirai', 30),
        ('Nawaz Sharif', 31),
        ('Nelson Mandela', 32),
        ('Osama bin Laden', 33),
        ('Oscar Pistorius', 34),
        ('Phil Spector', 35),
        ('Prince William', 36),
        ('Robert Mugabe', 37),
        ('Rupert Murdoch', 38),
        ('Saddam Hussein', 39),
        ('Sarah Palin', 40),
        ('Silvio Berlusconi', 41),
        ('Steve Jobs', 42),
        ('Taliban', 43),
        ('Ted Cruz', 44),
        ('Tiger Woods', 45),
        ('WikiLeaks', 46)
    ]
}
